package kuvioton.adt

sealed trait SimpleAdt
case class A1(value1: String, value2: Int) extends SimpleAdt
case class A2(value1: String, value2: Int) extends SimpleAdt

sealed trait StupidAdt

case class B1(value1: String, value2: Int) extends StupidAdt
case class B2(value1: String, value2: Int) extends StupidAdt
case class B3(value1: String, value2: Int) extends StupidAdt
case class B4(value1: String, value2: Int) extends StupidAdt
case class B5(value1: String, value2: Int) extends StupidAdt
case class B6(value1: String, value2: Int) extends StupidAdt
case class B7(value1: String, value2: Int) extends StupidAdt
case class B8(value1: String, value2: Int) extends StupidAdt
case class B9(value1: String, value2: Int) extends StupidAdt
case class B10(value1: String, value2: Int) extends StupidAdt
case class B11(value1: String, value2: Int) extends StupidAdt
case class B12(value1: String, value2: Int) extends StupidAdt
case class B13(value1: String, value2: Int) extends StupidAdt
case class B14(value1: String, value2: Int) extends StupidAdt
case class B15(value1: String, value2: Int) extends StupidAdt
case class B16(value1: String, value2: Int) extends StupidAdt
case class B17(value1: String, value2: Int) extends StupidAdt
case class B18(value1: String, value2: Int) extends StupidAdt
case class B19(value1: String, value2: Int) extends StupidAdt
case class B20(value1: String, value2: Int) extends StupidAdt
case class B21(value1: String, value2: Int) extends StupidAdt
case class B22(value1: String, value2: Int) extends StupidAdt
case class B23(value1: String, value2: Int) extends StupidAdt
case class B24(value1: String, value2: Int) extends StupidAdt
case class B25(value1: String, value2: Int) extends StupidAdt
case class B26(value1: String, value2: Int) extends StupidAdt
case class B27(value1: String, value2: Int) extends StupidAdt
case class B28(value1: String, value2: Int) extends StupidAdt
case class B29(value1: String, value2: Int) extends StupidAdt
case class B30(value1: String, value2: Int) extends StupidAdt
case class B31(value1: String, value2: Int) extends StupidAdt
case class B32(value1: String, value2: Int) extends StupidAdt
case class B33(value1: String, value2: Int) extends StupidAdt
case class B34(value1: String, value2: Int) extends StupidAdt
case class B35(value1: String, value2: Int) extends StupidAdt
case class B36(value1: String, value2: Int) extends StupidAdt
case class B37(value1: String, value2: Int) extends StupidAdt
case class B38(value1: String, value2: Int) extends StupidAdt
case class B39(value1: String, value2: Int) extends StupidAdt
case class B40(value1: String, value2: Int) extends StupidAdt
case class B41(value1: String, value2: Int) extends StupidAdt
case class B42(value1: String, value2: Int) extends StupidAdt
case class B43(value1: String, value2: Int) extends StupidAdt
case class B44(value1: String, value2: Int) extends StupidAdt
case class B45(value1: String, value2: Int) extends StupidAdt
case class B46(value1: String, value2: Int) extends StupidAdt
case class B47(value1: String, value2: Int) extends StupidAdt
case class B48(value1: String, value2: Int) extends StupidAdt
case class B49(value1: String, value2: Int) extends StupidAdt
case class B50(value1: String, value2: Int) extends StupidAdt
case class B51(value1: String, value2: Int) extends StupidAdt
case class B52(value1: String, value2: Int) extends StupidAdt
case class B53(value1: String, value2: Int) extends StupidAdt
case class B54(value1: String, value2: Int) extends StupidAdt
case class B55(value1: String, value2: Int) extends StupidAdt
case class B56(value1: String, value2: Int) extends StupidAdt
case class B57(value1: String, value2: Int) extends StupidAdt
case class B58(value1: String, value2: Int) extends StupidAdt
case class B59(value1: String, value2: Int) extends StupidAdt
case class B60(value1: String, value2: Int) extends StupidAdt
case class B61(value1: String, value2: Int) extends StupidAdt
case class B62(value1: String, value2: Int) extends StupidAdt
case class B63(value1: String, value2: Int) extends StupidAdt
case class B64(value1: String, value2: Int) extends StupidAdt
case class B65(value1: String, value2: Int) extends StupidAdt
case class B66(value1: String, value2: Int) extends StupidAdt
case class B67(value1: String, value2: Int) extends StupidAdt
case class B68(value1: String, value2: Int) extends StupidAdt
case class B69(value1: String, value2: Int) extends StupidAdt
case class B70(value1: String, value2: Int) extends StupidAdt
case class B71(value1: String, value2: Int) extends StupidAdt
case class B72(value1: String, value2: Int) extends StupidAdt
case class B73(value1: String, value2: Int) extends StupidAdt
case class B74(value1: String, value2: Int) extends StupidAdt
case class B75(value1: String, value2: Int) extends StupidAdt
case class B76(value1: String, value2: Int) extends StupidAdt
case class B77(value1: String, value2: Int) extends StupidAdt
case class B78(value1: String, value2: Int) extends StupidAdt
case class B79(value1: String, value2: Int) extends StupidAdt
case class B80(value1: String, value2: Int) extends StupidAdt
case class B81(value1: String, value2: Int) extends StupidAdt
case class B82(value1: String, value2: Int) extends StupidAdt
case class B83(value1: String, value2: Int) extends StupidAdt
case class B84(value1: String, value2: Int) extends StupidAdt
case class B85(value1: String, value2: Int) extends StupidAdt
case class B86(value1: String, value2: Int) extends StupidAdt
case class B87(value1: String, value2: Int) extends StupidAdt
case class B88(value1: String, value2: Int) extends StupidAdt
case class B89(value1: String, value2: Int) extends StupidAdt
case class B90(value1: String, value2: Int) extends StupidAdt
case class B91(value1: String, value2: Int) extends StupidAdt
case class B92(value1: String, value2: Int) extends StupidAdt
case class B93(value1: String, value2: Int) extends StupidAdt
case class B94(value1: String, value2: Int) extends StupidAdt
case class B95(value1: String, value2: Int) extends StupidAdt
case class B96(value1: String, value2: Int) extends StupidAdt
case class B97(value1: String, value2: Int) extends StupidAdt
case class B98(value1: String, value2: Int) extends StupidAdt
case class B99(value1: String, value2: Int) extends StupidAdt
case class B100(value1: String, value2: Int) extends StupidAdt
